version: 2

always_pending:
  title_regex: 'WIP'
  explanation: 'Work in progress...'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^:\+1:'
  reset_on_push:
    enabled: false

groups:
  dev:
    required: 2
    users:
      - namenu
      - antiline
      - earus
      - freekering
      - genesos
      - iamchanu

  design:
    conditions:
      files:
        - "UI/*"
    required: 1
    users:
      - jaeminbae
      - earus
      - freekering
      - namenu
